print('Hello Two')
print('change server')
print('lalala')
print('doubushi')
print('ri')
print('yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy')
print('wwwwwwwwwwwwwwwwwwwww')
print('tttttttttttttt')
print('jjjjjjjjjjjjjjjjjjjjjj')
print('nnnnnnnnnnnnnnnnnnnnnnnn')
print('new')
